image: atlassian/default-image:latest

pipelines:
  branches:
    public:
      - step:
          script:
          - git remote add sync git@github.com:Integral-Technology-Solutions/terraform-provider-uptime.git
          - git checkout $BITBUCKET_BRANCH
          - git pull
          - git push sync $BITBUCKET_BRANCH